language: python

python:
  - "2.7"

# command to install dependencies
install:

# command to run tests
script:
  - ./build.sh
  - pip install dist/*
  - ./test/test_draw.py
  - ./test/test_localTypes.py
  - ./test/test_polygon.py
  - pip uninstall -y blocksWorld
